FROM golang:1.18-alpine

RUN apk add musl-dev
RUN apk add libc-dev
RUN apk add gcc

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY ./ /app

RUN go build -o /matrixhook

ARG MATRIX_HOMESERVER
ARG MATRIX_USERNAME
ARG MATRIX_PASSWORD
ARG MATRIX_ROOM_ID
ARG WEBSERVER_PRESHARED_KEY

RUN sh .docker/env.sh MATRIX_HOMESERVER=$MATRIX_HOMESERVER MATRIX_USERNAME=$MATRIX_USERNAME MATRIX_PASSWORD=$MATRIX_PASSWORD MATRIX_ROOM_ID=$MATRIX_ROOM_ID WEBSERVER_HOST=0.0.0.0 WEBSERVER_PORT=8080 WEBSERVER_PRESHARED_KEY=$WEBSERVER_PRESHARED_KEY

EXPOSE 8080

CMD ["/matrixhook"]
